---
- name: Install zaw
  git:
    repo=ssh://git@github.com/zsh-users/zaw.git
    dest={{ zsh_plugin_home }}/zaw
  tags: zsh-zaw

- name: Install zsh-notify
  git:
    repo=ssh://git@github.com/marzocchi/zsh-notify.git
    dest={{ zsh_plugin_home }}/zsh-notify
  tags: zsh-notify

#- name: Create a directory for imcremental completion on zsh
#  file:
#    path={{ zsh_plugin_home }}/incr
#    state=directory
#  tags: zsh-incr
#
#- name: Install imcremental completion on zsh
#  get_url:
#    url=http://mimosa-pudica.net/src/incr-0.2.zsh
#    dest={{ zsh_plugin_home }}/incr/incr-0.2.zsh
#  tags: zsh-incr

- name: Install Prezto
  git:
    repo=ssh://git@github.com/sorin-ionescu/prezto.git
    dest={{ zsh_prezto_home }}
    recursive=yes

- name: Create symlinks to zsh config files
  file:
    src={{ zsh_prezto_home }}/runcoms/{{ item }}
    dest=~/.{{ item }}
    state=link
  with_items: zsh_prezto_config_files

- name: Deploy rc files
  template:
    src={{ item }}.j2
    dest=~/.{{ item }}
  with_items: zsh_prezto_deploy_files
  tags: zsh-rc

