---
- name: Create autoload directory
  file:
    path={{ vim_home }}/autoload
    state=directory

- name: Install Vim-Plug
  get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest={{ vim_home }}/autoload/plug.vim

- name: Create .vimrc
  template:
    src=.vimrc.j2
    dest=~/.vimrc
  tags: vim-vimrc

- name: Build vimproc
  command: make
    chdir={{ vimproc_home }}
    creates={{ vimproc_home }}/autoload/{{ vimproc_so }}

